/**
 * Generate the provisional leaf assets in src/leaf/assets/.
 *
 * These are ANALYTIC STAND-INS, not fits to imagery. They exist so both browser
 * tools are buildable and reviewable before the NeuraLeaf fitting pipeline
 * (tools/neuraleaf/) has run, and every asset it writes carries "provisional": true
 * so nothing published can rest on them by accident. This script is the record of
 * exactly how they were constructed — it is not a substitute for a real fit.
 *
 * The outline is a beta-shaped half-width sweep, w(y) ∝ (y/L)^a (1 - y/L)^b, which
 * is the standard way to get the obovate/spatulate silhouette of an Arabidopsis
 * rosette leaf: narrow at the petiole junction, widest past the middle, rounded tip.
 * Peak position is a/(a+b), so a = 1.6, b = 1.0 puts the widest chord at 0.62 L.
 *
 * Blade dimensions are ordinary Col-0 values and the mature leaf is set to 15 mm
 * long to match this repo's existing calibration (results/tables/T3: leaf 1.5 cm
 * spans 52 lattice cells).
 *
 *   node tools/leaf-assets/make_provisional.mjs
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../../src/leaf/assets');

const round = (v, dp = 4) => Number(v.toFixed(dp));

/**
 * Closed outline of a blade, counter-clockwise, base at y = 0 and tip at y = L.
 * Walks up the right margin and back down the left, so the first point is the base.
 */
function blade({ length, width, a, b, ripple = 0, rippleCycles = 6, n = 120 }) {
  const peak = a / (a + b);
  const norm = Math.pow(peak, a) * Math.pow(1 - peak, b);
  const halfWidthAt = (u) => {
    const base = (Math.pow(u, a) * Math.pow(1 - u, b)) / norm;
    const wave = ripple ? 1 + ripple * Math.sin(rippleCycles * Math.PI * u) : 1;
    return (width / 2) * base * wave;
  };

  const right = [];
  const left = [];
  for (let k = 0; k <= n; k++) {
    const u = k / n;
    const y = u * length;
    const w = halfWidthAt(u);
    right.push([round(w), round(y)]);
    left.push([round(-w), round(y)]);
  }
  // Drop the duplicated base and tip points where the two margins meet.
  return [...right, ...left.reverse().slice(1, -1)];
}

/** Straight midrib from base to tip. */
function midrib(length, n = 9) {
  return Array.from({ length: n + 1 }, (_, k) => [0, round((k / n) * length)]);
}

const assets = [
  {
    id: 'provisional-cotyledon',
    label: 'Cotyledon (provisional, 2.5 mm)',
    geometry: { length: 2.5, width: 2.0, a: 1.1, b: 1.0, n: 96 },
    thicknessMm: 0.15,
    profile: [
      [0, 0],
      [1, 0],
    ],
    camber: [
      [-1, 0],
      [0, 0],
      [1, 0],
    ],
    note: 'Near-circular cotyledon blade, flat. Analytic stand-in.',
  },
  {
    id: 'provisional-juvenile',
    label: 'Juvenile leaf (provisional, 6 mm)',
    geometry: { length: 6, width: 4, a: 1.4, b: 1.0, n: 120 },
    thicknessMm: 0.18,
    profile: [
      [0, 0],
      [0.5, 0.08],
      [1, 0.1],
    ],
    camber: [
      [-1, 0.06],
      [-0.5, 0.01],
      [0, 0],
      [0.5, 0.01],
      [1, 0.06],
    ],
    note: 'First true leaf, faint upward cup. Analytic stand-in.',
  },
  {
    id: 'provisional-mature-flat',
    label: 'Mature rosette leaf, flat (provisional, 15 mm)',
    geometry: { length: 15, width: 8, a: 1.6, b: 1.0, ripple: 0.04, n: 160 },
    thicknessMm: 0.21,
    profile: [
      [0, 0],
      [1, 0],
    ],
    camber: [
      [-1, 0],
      [0, 0],
      [1, 0],
    ],
    note:
      'Flat 15 mm blade sized to the T3 calibration (1.5 cm ↔ 52 cells). This is the ' +
      'like-for-like replacement for the stampEllipse reference geometry.',
  },
  {
    id: 'provisional-mature-cupped',
    label: 'Mature rosette leaf, cupped (provisional, 15 mm)',
    geometry: { length: 15, width: 8, a: 1.6, b: 1.0, ripple: 0.04, n: 160 },
    thicknessMm: 0.21,
    profile: [
      [0, 0],
      [0.3, 0.35],
      [0.7, 0.6],
      [1, 0.55],
    ],
    camber: [
      [-1, 0.9],
      [-0.6, 0.35],
      [-0.25, 0.06],
      [0, 0],
      [0.25, 0.06],
      [0.6, 0.35],
      [1, 0.9],
    ],
    note:
      'Same blade as provisional-mature-flat, arched along the midrib and cupped ' +
      'across it. The pair isolates deformation at fixed outline.',
  },
];

mkdirSync(OUT, { recursive: true });

for (const a of assets) {
  const asset = {
    id: a.id,
    label: a.label,
    provisional: true,
    source: {
      series: 'provisional',
      note: `${a.note} Generated by tools/leaf-assets/make_provisional.mjs — NOT a fit to imagery.`,
    },
    outline: blade(a.geometry),
    midrib: midrib(a.geometry.length),
    profile: a.profile,
    camber: a.camber,
    thicknessMm: a.thicknessMm,
  };
  const path = join(OUT, `${a.id}.json`);
  writeFileSync(path, JSON.stringify(asset, null, 2) + '\n');
  console.log(`${a.id}: ${asset.outline.length} outline points → ${path}`);
}
